language: ruby
cache: bundler
rvm:
- 2.2
sudo: false
script: true
deploy:
  provider: rubygems
  api_key:
    secure: jEc3woY9TQYOAVbVRINM2qsZNa5PeV9c8ci7GWyF9nabOnnPVH7yDsLgA1amSyJN6KCMyZ8yXeCLWrVDLXJiuGXRUFCDsciu05G8o3vVr1Z8ytntOjalhDXY5Tq2hxeILRv6Ls665nqrxpbFJYW2ovDKJx+03lCAzn71yC+hmVM=
  gem: build-cloud
  on:
    tags: true
    repo: scalefactory/build-cloud
